from __future__ import annotations
from typing import Protocol, List, Dict, Any, Optional

class EmbeddingsInterface(Protocol):
    provider: str
    model_name: str
    dim: int

    def embed_text(self, text: str) -> List[float]: ...
    def embed_batch(self, texts: List[str]) -> List[List[float]]: ...

class VectorStoreInterface(Protocol):
    provider: str
    dim: int

    def add(self, doc_id: str, embedding: List[float], metadata: Dict[str, Any]) -> None: ...
    def batch_add(self, items: List[Dict[str, Any]]) -> None: ...
    def query(self, embedding: List[float], top_k: int = 5, filters: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]: ...
    def stats(self) -> Dict[str, Any]: ...

class RAGInterface(Protocol):
    def retrieve(self, query: str, top_k: int = 5, filters: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]: ...
